name: Metrics
on:
  schedule: [{cron: "0 */2 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: k8s-runner-supporterino
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_lines: yes
          config_timezone: Europe/Berlin
          config_display: columns
          # Base plugin
          base: header, repositories, metadata, activity
          base_indepth: true
          # Achievements
          plugin_achievements: true
          plugin_achievements_display: detailed
          # Habits
          plugin_habits: true
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: true
          plugin_habits_charts: true
          # Languages
          plugin_languages: true
          plugin_languages_indepth: true
          # Follow-up
          plugin_followup: true
          plugin_followup_sections: user, repositories
          plugin_followup_indepth: true
          # Gist
          plugin_gists: true
          # Discussions
          plugin_discussions: true
          # Calendar
          plugin_isocalendar: true
